[package]
name = "learn-bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.10.0"
rand = "0.8.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html